[build]
  base = "."
  publish = "client/build"
  command = "cd client && npm install && CI=false DISABLE_ESLINT_PLUGIN=true TSC_COMPILE_ON_ERROR=true npm run build"

[build.environment]
  NODE_VERSION = "18.20.6"
  NODE_ENV = "production"
  NETLIFY_USE_YARN = "false"
